In [ ]:
# NUMPY ###

In [ ]:
# 4. Import numpy, create an array arr = np.array([1,2,3,4,5]). Print its mean, sum, and max.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr.mean()

np.float64(3.0)

In [ ]:
arr.sum()

np.int64(15)

In [ ]:
arr.max()

np.int64(5)

In [ ]:
# 5. Create a 2D array (3x3) and print its shape.

In [ ]:
# 6. Multiply every element in arr by 2 (no loop — just use the array directly).

In [ ]:
arr *2

array([ 2,  4,  6,  8, 10])

In [ ]:
# Pandas — Intro & Inspection

In [ ]:
# 7. Create a small DataFrame from a dictionary with columns name, age, city (3-4 rows).

In [ ]:
import pandas as pd

In [ ]:
dicts = [
    {'name': 'John', 'age': 25, 'city': 'New York'},
    {'name': 'Alice', 'age': None, 'city': 'Los Angeles'},
    {'name': 'Bob', 'age': 22, 'city': None},
    {'name': 'Luke', 'age': 31, 'city': 'Urgench'},
    {'name': 'Anna', 'age': 28, 'city': 'London'},
    {'name': 'Tom', 'age': None, 'city': 'Paris'},
    {'name': 'Kate', 'age': 29, 'city': 'Berlin'}
    ]

In [ ]:
df = pd.DataFrame(dicts)

In [ ]:
# 8. Use .head(), .info(), and .describe() on it — explain briefly what each one tells you.

In [ ]:
df.head()

    name   age         city
0   John  25.0     New York
1  Alice   NaN  Los Angeles
2    Bob  22.0         None
3   Luke  31.0      Urgench
4   Anna  28.0       London

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      object
 1   age     5 non-null      float64
 2   city    6 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [ ]:
df.describe()

             age
count   5.000000
mean   27.000000
std     3.535534
min    22.000000
25%    25.000000
50%    28.000000
75%    29.000000
max    31.000000

In [ ]:
# 9. Print just the age column. Then print the name and city columns together.

In [ ]:
df.age

0    25
1    30
2    22
3    31
4    28
5    35
6    29
Name: age, dtype: int64

In [ ]:
df['age']

0    25
1    30
2    22
3    31
4    28
5    35
6    29
Name: age, dtype: int64

In [ ]:
df[['city', 'name']]

          city   name
0     New York   John
1  Los Angeles  Alice
2      Chicago    Bob
3      Urgench   Luke
4       London   Anna
5        Paris    Tom
6       Berlin   Kate

In [ ]:
# Pandas — Cleaning

In [ ]:
# 10. Given a DataFrame with some missing values (NaN), check how many missing values exist per column.

In [ ]:
df['age'].notna().value_counts()

age
True     5
False    2
Name: count, dtype: int64

In [ ]:
df['city'].notna().value_counts()

city
True     6
False    1
Name: count, dtype: int64

In [ ]:
df['name'].notna().value_counts()

name
True    7
Name: count, dtype: int64

In [ ]:
df.isna().sum()    # counts none values for each column

name    0
age     2
city    1
dtype: int64

In [ ]:
# 11. Drop rows with any missing values. Then, separately, fill missing values with 0 instead.

In [ ]:
df_d = df.dropna().copy()
df_d['age'] = df_d['age'].astype(int)

In [ ]:
df_d

   name  age      city
0  John   25  New York
3  Luke   31   Urgench
4  Anna   28    London
6  Kate   29    Berlin

In [ ]:
df_f = df.fillna(0).copy()     # gives 0 for none values
df_f['age'] = df_f['age'].astype(int)

In [ ]:
df_f

    name  age     location
0   John   25     New York
1  Alice    0  Los Angeles
2    Bob   22            0
3   Luke   31      Urgench
4   Anna   28       London
5    Tom    0        Paris
6   Kate   29       Berlin

In [ ]:
# 12. Rename a column (e.g. "city" → "location").

In [ ]:
df = df.rename(columns = {'city': 'location'})

In [ ]:
df

    name   age     location
0   John  25.0     New York
1  Alice   NaN  Los Angeles
2    Bob  22.0         None
3   Luke  31.0      Urgench
4   Anna  28.0       London
5    Tom   NaN        Paris
6   Kate  29.0       Berlin

In [ ]:
# Pandas — Analysis

In [ ]:
# 13. Given your DataFrame, filter rows where age > 25.

In [ ]:
df[df['age'] > 25]

   name   age     city
3  Luke  31.0  Urgench
4  Anna  28.0   London
6  Kate  29.0   Berlin

In [ ]:
# 14. Group by city and get the average age per city.

In [ ]:
df.groupby('city')['age'].mean()

city
Berlin         29.0
London         28.0
Los Angeles     NaN
New York       25.0
Paris           NaN
Urgench        31.0
Name: age, dtype: float64

In [ ]:
# 15. Sort the DataFrame by age descending.

In [ ]:
df.sort_values('age', ascending = False)

    name   age         city
3   Luke  31.0      Urgench
6   Kate  29.0       Berlin
4   Anna  28.0       London
0   John  25.0     New York
2    Bob  22.0         None
1  Alice   NaN  Los Angeles
5    Tom   NaN        Paris