In [ ]:
### LIBRARIES ###

In [ ]:
# NUMPY #

In [ ]:
import random
random.randint(100,200)

182

In [ ]:
salary_list = [random.randint(50000, 100000) for _ in range(1000000)]

In [ ]:
import statistics
statistics.mean(salary_list)

74994.635071

In [ ]:
%%timeit
statistics.mean(salary_list)

The slowest run took 6.32 times longer than the fastest. This could mean that an intermediate result is being cached.
618 ms ± 465 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
import numpy as np
np.mean(salary_list)

np.float64(74994.635071)

In [ ]:
%%timeit
np.mean(salary_list)

247 ms ± 77.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
my_array = np.array([1,2,3,4,])

In [ ]:
my_array

array([1, 2, 3, 4])

In [ ]:
my_array.mean()

np.float64(2.5)

In [ ]:
job_titles = np.array (['Data analyst', 'Data scientist', 'Data engineer', 'AI'])
base_salaries = np.array ([60000, 80000, 75000, 90000])
bonus_rates = np.array ([.05, .1, .08, .12])

In [ ]:
total_salaries = base_salaries * (bonus_rates +1)
total_salaries

array([ 63000.,  88000.,  81000., 100800.])

In [ ]:
np.mean(total_salaries)

np.float64(83200.0)

In [ ]:
None

In [ ]:
type(None)

NoneType

In [ ]:
type(np.nan)

float

In [ ]:
job_titles = np.array (['Data analyst', 'Data scientist', 'Data engineer', 'AI', 'BI anayst'])
base_salaries = np.array ([60000, 80000, 75000, 90000, np.nan])
bonus_rates = np.array ([.05, .1, .08, .12, np.nan])

In [ ]:
total_salaries = base_salaries * (bonus_rates +1)
total_salaries

array([ 63000.,  88000.,  81000., 100800.,     nan])

In [ ]:
np.nanmean(total_salaries)

np.float64(83200.0)

In [ ]:
## PANDAS #######

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df['total_rooms']

0       3885.0
1       1510.0
2       3589.0
3         67.0
4       1241.0
         ...
2995    1450.0
2996    5257.0
2997     956.0
2998      96.0
2999    1765.0
Name: total_rooms, Length: 3000, dtype: float64

In [ ]:
df['total_rooms'][0]

np.float64(3885.0)

In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (3.32.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.27.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset('lukebarousse/data_jobs')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['job_title_short', 'job_title', 'job_location', 'job_via', 'job_schedule_type', 'job_work_from_home', 'search_location', 'job_posted_date', 'job_no_degree_mention', 'job_health_insurance', 'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg', 'company_name', 'job_skills', 'job_type_skills'],
        num_rows: 785741
    })
})

In [ ]:
dataset['train']

Dataset({
    features: ['job_title_short', 'job_title', 'job_location', 'job_via', 'job_schedule_type', 'job_work_from_home', 'search_location', 'job_posted_date', 'job_no_degree_mention', 'job_health_insurance', 'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg', 'company_name', 'job_skills', 'job_type_skills'],
    num_rows: 785741
})

In [ ]:
type(dataset['train'])

datasets.arrow_dataset.Dataset

In [ ]:
dataset['train'].to_pandas()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
df = dataset['train'].to_pandas()

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [ ]:
df.head(7)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."

In [ ]:
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
df['job_location'].head()

0                   Watertown, CT
1    Guadalajara, Jalisco, Mexico
2                 Berlin, Germany
3                 San Antonio, TX
4                  Washington, DC
Name: job_location, dtype: object

In [ ]:
df[['job_health_insurance']]

        job_health_insurance
0                      False
1                      False
2                      False
3                      False
4                      False
...                      ...
785736                 False
785737                 False
785738                 False
785739                 False
785740                 False

[785741 rows x 1 columns]

In [ ]:
df[['job_health_insurance', 'job_location']]

        job_health_insurance                         job_location
0                      False                        Watertown, CT
1                      False         Guadalajara, Jalisco, Mexico
2                      False                      Berlin, Germany
3                      False                      San Antonio, TX
4                      False                       Washington, DC
...                      ...                                  ...
785736                 False                            Singapura
785737                 False                   Bad Rodach, Jerman
785738                 False                             Malaysia
785739                 False  Newark, New Jersey, Amerika Serikat
785740                 False                                India

[785741 rows x 2 columns]

In [ ]:
df[['job_health_insurance', 'job_location']].head()

   job_health_insurance                  job_location
0                 False                 Watertown, CT
1                 False  Guadalajara, Jalisco, Mexico
2                 False               Berlin, Germany
3                 False               San Antonio, TX
4                 False                Washington, DC

In [ ]:
df.iloc[90]  #  shows row 90 info

job_title_short                                             Data Scientist
job_title                                                   Data Scientist
job_location                                                     Australia
job_via                                                via BeBee Australia
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                  Australia
job_posted_date                                        2023-11-25 13:12:03
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                      Australia
salary_rate                                                           None
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                           Concurrent Technologies Corporation
job_skills               ['python', 'sql', 'r', 'java', 'bash', 'react'...
job_type_skills          {'analyst_tools': ['tableau'], 'libraries': ['...
Name: 90, dtype: object

In [ ]:
df.iloc[90:96]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
90,Data Scientist,Data Scientist,Australia,via BeBee Australia,Full-time,False,Australia,2023-11-25 13:12:03,False,False,Australia,None,NaN,NaN,Concurrent Technologies Corporation,"['python', 'sql', 'r', 'java', 'bash', 'react'...","{'analyst_tools': ['tableau'], 'libraries': ['..."
91,Data Scientist,Data Scientist,"Temuco, Chile",via BeBee Chile,Full-time,False,Chile,2023-01-06 14:07:40,False,False,Chile,None,NaN,NaN,Talently,"['sql', 'python', 'tensorflow', 'numpy', 'pand...","{'analyst_tools': ['excel', 'tableau'], 'libra..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
93,Data Analyst,IT Finance / TBM Data Analyst - Remote | WFH,Anywhere,via LinkedIn,Full-time,True,"New York, United States",2023-06-10 13:00:05,False,False,United States,None,NaN,NaN,Get It Recruit - Information Technology,"['oracle', 'azure', 'power bi', 'excel', 'word...","{'analyst_tools': ['power bi', 'excel', 'word'..."
94,Data Engineer,Data Engineer - Cloud Operations,"Lehi, UT",via LinkedIn,Full-time,False,"Texas, United States",2023-03-18 13:08:17,False,False,United States,None,NaN,NaN,Adobe,"['javascript', 'python', 'sql', 'aws', 'azure'...","{'analyst_tools': ['power bi', 'tableau'], 'cl..."
95,Data Engineer,Data Engineer,"Mumbai, Maharashtra, India",via Crimsoniteam.freshteam.com,Full-time,False,India,2023-07-31 13:35:48,False,False,India,None,NaN,NaN,Crimson Interactive Inc,"['nosql', 'mongodb', 'mongodb', 'elasticsearch...","{'analyst_tools': ['tableau'], 'databases': ['..."

In [ ]:
df.iloc[90:96, 0]  # info for rows 90-95 in the 1st column

90    Data Scientist
91    Data Scientist
92     Data Engineer
93      Data Analyst
94     Data Engineer
95     Data Engineer
Name: job_title_short, dtype: object

In [ ]:
df.iloc[90:96, 0:3]  # for columns 1 2 3

,job_title_short,job_title,job_location
90,Data Scientist,Data Scientist,Australia
91,Data Scientist,Data Scientist,"Temuco, Chile"
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere
93,Data Analyst,IT Finance / TBM Data Analyst - Remote | WFH,Anywhere
94,Data Engineer,Data Engineer - Cloud Operations,"Lehi, UT"
95,Data Engineer,Data Engineer,"Mumbai, Maharashtra, India"

In [ ]:
df [['job_title_short', 'job_title']].iloc[90:96]

   job_title_short                                     job_title
90  Data Scientist                                Data Scientist
91  Data Scientist                                Data Scientist
92   Data Engineer       Remote - Data Engineer - Permanent - W2
93    Data Analyst  IT Finance / TBM Data Analyst - Remote | WFH
94   Data Engineer              Data Engineer - Cloud Operations
95   Data Engineer                                 Data Engineer

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [ ]:
df.job_title_short.unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [ ]:
df.job_title_short == 'Data Analyst'

0         False
1          True
2         False
3         False
4         False
          ...
785736    False
785737     True
785738    False
785739    False
785740    False
Name: job_title_short, Length: 785741, dtype: bool

In [ ]:
df[df.job_title_short == 'Data Analyst']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
12,Data Analyst,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship,False,France,2023-12-22 13:24:41,False,False,France,None,NaN,NaN,Engie,"['sql', 'php', 'excel', 'power bi', 'sap', 'ji...","{'analyst_tools': ['excel', 'power bi', 'sap']..."
18,Data Analyst,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-10-16 13:36:54,False,False,Poland,None,NaN,NaN,Glovo,"['sql', 'python', 'r', 'redshift', 'pandas', '...","{'analyst_tools': ['excel', 'looker', 'tableau..."
31,Data Analyst,Stage - Data Analyst F/H,"Paris, France",via LinkedIn,Full-time and Internship,False,France,2023-10-19 13:59:31,False,False,France,None,NaN,NaN,GROUPE BON MARCHÉ : Le Bon Marché Rive Gauche ...,['sql'],{'programming': ['sql']}
34,Data Analyst,Data Analyst als Marketing Manager Automation ...,"Erlangen, Germany",via Central Illinois Proud Jobs,Full-time,False,Germany,2023-02-23 13:31:28,True,False,Germany,None,NaN,NaN,DEFACTO GmbH,['sap'],{'analyst_tools': ['sap']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,None,NaN,NaN,Amul,None,None
785717,Data Analyst,Data & Analytics Architect (w/m/x),"Erfurt, Jerman",melalui LinkedIn,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,NTT DATA DACH,"['aws', 'azure']","{'cloud': ['aws', 'azure']}"
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."

In [ ]:
df[(df.job_title_short == 'Data Analyst') & (df.salary_year_avg > 100000)]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.0,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '..."
1555,Data Analyst,Data Analyst/Engineer (M/F/D),"Aveiro, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-04-25 13:27:25,False,False,Portugal,year,111175.0,NaN,Bosch Group,"['databricks', 'spark']","{'cloud': ['databricks'], 'libraries': ['spark']}"
1681,Data Analyst,Data Analyst,"Irvine, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-03-23 13:01:14,False,True,United States,year,111175.0,NaN,Western Digital,"['sql', 'tableau', 'power bi', 'excel']","{'analyst_tools': ['tableau', 'power bi', 'exc..."
1684,Data Analyst,Data Analyst - Data17829,"Tampa, FL",via Indeed,Full-time,False,"Florida, United States",2023-07-18 13:02:09,True,True,United States,year,120000.0,NaN,Acrisure,"['shell', 'sql', 'azure', 'databricks', 'linux']","{'cloud': ['azure', 'databricks'], 'os': ['lin..."
1867,Data Analyst,Data Integration Analyst (West Coast/Chicago),"Chicago, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-07-18 13:01:47,False,False,United States,year,101500.0,NaN,Forsta,"['php', 'python', 'express']","{'programming': ['php', 'python'], 'webframewo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783588,Data Analyst,Data Analytics Manager,"Chicago, IL",via Ladders,Full-time,False,"Illinois, United States",2023-01-09 06:01:18,False,False,United States,year,125000.0,NaN,"United Air Lines, Inc","['sql', 'r', 'python', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
783866,Data Analyst,Lead Credit Bureau Data Analyst,"Des Plaines, IL",via Ladders,Full-time,False,"Illinois, United States",2023-06-02 06:02:06,False,True,United States,year,115000.0,NaN,Discover Financial Services,['unix'],{'os': ['unix']}
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
785187,Data Analyst,Data Analyst,"Lisbon, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-06-07 06:30:33,False,False,Portugal,year,111175.0,NaN,Farfetch,"['sql', 'python', 'r', 'looker']","{'analyst_tools': ['looker'], 'programming': [..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None

In [ ]:
df[(df.job_title_short == 'Data Analyst') | (df.salary_year_avg > 100000)]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
12,Data Analyst,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship,False,France,2023-12-22 13:24:41,False,False,France,None,NaN,NaN,Engie,"['sql', 'php', 'excel', 'power bi', 'sap', 'ji...","{'analyst_tools': ['excel', 'power bi', 'sap']..."
18,Data Analyst,Data Analyst,"Warsaw, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-10-16 13:36:54,False,False,Poland,None,NaN,NaN,Glovo,"['sql', 'python', 'r', 'redshift', 'pandas', '...","{'analyst_tools': ['excel', 'looker', 'tableau..."
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
31,Data Analyst,Stage - Data Analyst F/H,"Paris, France",via LinkedIn,Full-time and Internship,False,France,2023-10-19 13:59:31,False,False,France,None,NaN,NaN,GROUPE BON MARCHÉ : Le Bon Marché Rive Gauche ...,['sql'],{'programming': ['sql']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,None,NaN,NaN,Amul,None,None
785717,Data Analyst,Data & Analytics Architect (w/m/x),"Erfurt, Jerman",melalui LinkedIn,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,NTT DATA DACH,"['aws', 'azure']","{'cloud': ['aws', 'azure']}"
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."

In [ ]:
df.salary_year_avg.notna()

0         False
1         False
2         False
3         False
4         False
          ...
785736    False
785737    False
785738    False
785739    False
785740    False
Name: salary_year_avg, Length: 785741, dtype: bool

In [ ]:
df[(df.job_title_short == 'Data Analyst') & (df.salary_year_avg.notna())]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
180,Data Analyst,Data Analyst III,"Dos Palos, CA",via My ArkLaMiss Jobs,Full-time,False,"California, United States",2023-02-27 13:00:39,False,True,United States,year,90250.0,NaN,California Health & Wellness,"['excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint']}"
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.0,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '..."
988,Data Analyst,DATA ANALYST (ONSITE),"Springfield, MA",via Indeed,Full-time,False,"New York, United States",2023-11-21 13:00:13,False,False,United States,year,62623.0,NaN,Springfield Public Schools,"['sql', 'excel', 'tableau']","{'analyst_tools': ['excel', 'tableau'], 'progr..."
1413,Data Analyst,Junior BI Developer,"Atlanta, GA",via Ai-Jobs.net,Full-time,False,Georgia,2023-10-31 13:57:41,False,True,United States,year,71300.0,NaN,Guidehouse,"['sql', 'excel', 'power bi']","{'analyst_tools': ['excel', 'power bi'], 'prog..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
784423,Data Analyst,Sales Data Analyst,"Juriquilla, Qro., Mexico",via Ai-Jobs.net,Full-time,False,Mexico,2023-01-05 06:43:20,False,False,Mexico,year,80850.0,NaN,Charger Logistics Inc,"['tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi']}"
784882,Data Analyst,Merchandising Analyst (Data Analyst),"Denton, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-04 15:29:24,False,False,United States,year,87500.0,NaN,Insight Global,"['sql', 'vba', 'tableau', 'excel', 'alteryx']","{'analyst_tools': ['tableau', 'excel', 'altery..."
785187,Data Analyst,Data Analyst,"Lisbon, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-06-07 06:30:33,False,False,Portugal,year,111175.0,NaN,Farfetch,"['sql', 'python', 'r', 'looker']","{'analyst_tools': ['looker'], 'programming': [..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [ ]:
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [ ]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
df.job_posted_date.dt.month

0          6
1          1
2         10
3          7
4          8
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_date, Length: 785741, dtype: int32

In [ ]:
df['job_posted_date'] = df.job_posted_date.dt.month

In [ ]:
df.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  int32
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), int32(1), object(11)
memory usage: 83.2+ MB

In [ ]:
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [ ]:
print(df['job_posted_date'].iloc[0])
print(type(df['job_posted_date'].iloc[0]))

1970-01-01 00:00:00.000000006
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [ ]:
df['job_posted_date'].head()

0   1970-01-01 00:00:00.000000006
1   1970-01-01 00:00:00.000000001
2   1970-01-01 00:00:00.000000010
3   1970-01-01 00:00:00.000000007
4   1970-01-01 00:00:00.000000008
Name: job_posted_date, dtype: datetime64[ns]

In [ ]:
pd.to_datetime(df.job_posted_date)

0        1970-01-01 00:00:00.000000006
1        1970-01-01 00:00:00.000000001
2        1970-01-01 00:00:00.000000010
3        1970-01-01 00:00:00.000000007
4        1970-01-01 00:00:00.000000008
                      ...
785736   1970-01-01 00:00:00.000000003
785737   1970-01-01 00:00:00.000000003
785738   1970-01-01 00:00:00.000000003
785739   1970-01-01 00:00:00.000000003
785740   1970-01-01 00:00:00.000000003
Name: job_posted_date, Length: 785741, dtype: datetime64[ns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [ ]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",1970-01-01 00:00:00.000000006,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,1970-01-01 00:00:00.000000001,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,1970-01-01 00:00:00.000000010,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",1970-01-01 00:00:00.000000007,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,1970-01-01 00:00:00.000000008,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,1970-01-01 00:00:00.000000003,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,1970-01-01 00:00:00.000000003,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,1970-01-01 00:00:00.000000003,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,1970-01-01 00:00:00.000000003,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,1970-01-01 00:00:00.000000003,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
df.sort_values('job_posted_date')

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
203943,Data Scientist,Data Scientist,"Denver, CO",via Adzuna,Full-time,False,Sudan,1970-01-01 00:00:00.000000001,False,True,Sudan,None,NaN,NaN,BP,"['python', 'azure', 'aws']","{'cloud': ['azure', 'aws'], 'programming': ['p..."
282667,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,1970-01-01 00:00:00.000000001,False,False,India,None,NaN,NaN,ACI Worldwide,"['sql', 'power bi', 'tableau', 'dax']","{'analyst_tools': ['power bi', 'tableau', 'dax..."
93472,Senior Data Engineer,Senior Data Engineer,"Western Australia, Australia",via Jobrapido.com,Full-time,False,Australia,1970-01-01 00:00:00.000000001,False,False,Australia,None,NaN,NaN,Professional Search Group,"['sql', 't-sql', 'python', 'java', 'r', 'power...","{'analyst_tools': ['ssis', 'excel'], 'cloud': ..."
93471,Data Scientist,Data Scientist II,Arizona,via Karkidi,Full-time,False,Sudan,1970-01-01 00:00:00.000000001,False,True,Sudan,None,NaN,NaN,Farmers Insurance Group,None,None
282665,Data Scientist,Material Data Specialist(Coupa),"Monterrey, Nuevo Leon, Mexico",via BeBee México,Full-time,False,Mexico,1970-01-01 00:00:00.000000001,True,False,Mexico,None,NaN,NaN,Enroute,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413720,Data Scientist,Data Science- GPT/LLM,"Kolkata, West Bengal, India",via LinkedIn,Full-time,False,India,1970-01-01 00:00:00.000000012,False,False,India,None,NaN,NaN,LTIMindtree,"['python', 'r', 'pytorch', 'tensorflow', 'keras']","{'libraries': ['pytorch', 'tensorflow', 'keras..."
731675,Senior Data Engineer,Senior Data Engineer,"Cluj-Napoca, Romania",via LinkedIn,Full-time,False,Romania,1970-01-01 00:00:00.000000012,False,False,Romania,None,NaN,NaN,Energy Jobline,"['sql', 't-sql', 'sql server', 'azure', 'oracl...","{'analyst_tools': ['ssis', 'power bi'], 'cloud..."
467337,Software Engineer,Principal iOS Software Engineer,"La Florida, Chile",via BeBee,Full-time,False,Chile,1970-01-01 00:00:00.000000012,False,False,Chile,None,NaN,NaN,Salesforce,"['swift', 'excel', 'slack']","{'analyst_tools': ['excel'], 'programming': ['..."
731685,Machine Learning Engineer,Machine-Learning-Engineer (m/w/d),"Eisenstadt, Austria",via BeBee,Full-time,False,Austria,1970-01-01 00:00:00.000000012,False,False,Austria,None,NaN,NaN,Nagarro GmbH,"['python', 'aws', 'azure', 'gcp', 'tensorflow'...","{'analyst_tools': ['excel'], 'cloud': ['aws', ..."
573693,Business Analyst,QA Engineer,"Ramos Mejía, Buenos Aires Province, Argentina",via BeBee,Full-time,False,Argentina,1970-01-01 00:00:00.000000012,True,False,Argentina,None,NaN,NaN,Veritran,['jira'],{'async': ['jira']}

In [ ]:
df = df.sort_values('job_posted_date')

In [ ]:
df.sort_values('job_posted_date', inplace=True)

In [ ]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
203943,Data Scientist,Data Scientist,"Denver, CO",via Adzuna,Full-time,False,Sudan,1970-01-01 00:00:00.000000001,False,True,Sudan,None,NaN,NaN,BP,"['python', 'azure', 'aws']","{'cloud': ['azure', 'aws'], 'programming': ['p..."
709496,Data Engineer,Data Engineer,"West Bromwich, UK",via My ArkLaMiss Jobs,Full-time,False,United Kingdom,1970-01-01 00:00:00.000000001,True,False,United Kingdom,None,NaN,NaN,X4 Group,None,None
709492,Senior Data Scientist,AIML - Senior Data Scientist - Siri and Inform...,"Santa Clara, CA",via Trabajo.org,Full-time,False,"California, United States",1970-01-01 00:00:00.000000001,False,True,United States,None,NaN,NaN,Apple Inc.,"['python', 'hadoop', 'spark']","{'libraries': ['hadoop', 'spark'], 'programmin..."
709486,Data Engineer,Data Engineer,"McLean, VA",via LinkedIn,Full-time,False,Georgia,1970-01-01 00:00:00.000000001,False,True,United States,None,NaN,NaN,Piper Companies,"['bash', 'python', 'java', 'scala', 'hadoop', ...","{'libraries': ['hadoop', 'spark', 'kafka'], 'o..."
30379,Senior Data Analyst,General Assurance Data Analytics – Manager,Singapore,via LinkedIn,Full-time,False,Singapore,1970-01-01 00:00:00.000000001,True,False,Singapore,None,NaN,NaN,PwC Singapore,"['sql', 'vba', 'tableau', 'qlik', 'power bi', ...","{'analyst_tools': ['tableau', 'qlik', 'power b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320501,Software Engineer,Junior Software Engineer,"Toronto, ON, Canada",via SimplyHired,Full-time,False,Canada,1970-01-01 00:00:00.000000012,False,False,Canada,None,NaN,NaN,San Data System,None,None
765254,Software Engineer,Onsite Network Security Support Engineer,"Nairobi, Kenya",via BeBee Kenya,Full-time,False,Kenya,1970-01-01 00:00:00.000000012,False,False,Kenya,None,NaN,NaN,NTT Ltd,None,None
439849,Senior Data Engineer,Senior Data Engineer,"Sydney NSW, Australia",via LinkedIn,Full-time,False,Australia,1970-01-01 00:00:00.000000012,False,False,Australia,None,NaN,NaN,Workforce Australia for Individuals,"['python', 'sql', 'aws', 'spark', 'airflow', '...","{'cloud': ['aws'], 'libraries': ['spark', 'air..."
447335,Data Scientist,Data Science + Python Midior,"Madrid, Spain",via BeBee,Full-time,False,Spain,1970-01-01 00:00:00.000000012,False,False,Spain,None,NaN,NaN,SG Tech,"['python', 'pandas', 'tensorflow']","{'libraries': ['pandas', 'tensorflow'], 'progr..."
573693,Business Analyst,QA Engineer,"Ramos Mejía, Buenos Aires Province, Argentina",via BeBee,Full-time,False,Argentina,1970-01-01 00:00:00.000000012,True,False,Argentina,None,NaN,NaN,Veritran,['jira'],{'async': ['jira']}

In [ ]:
df.sort_values('job_posted_date', ascending = False)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
573693,Business Analyst,QA Engineer,"Ramos Mejía, Buenos Aires Province, Argentina",via BeBee,Full-time,False,Argentina,1970-01-01 00:00:00.000000012,True,False,Argentina,None,NaN,NaN,Veritran,['jira'],{'async': ['jira']}
92428,Data Analyst,SAP Data Analyst (Contract),"Plano, TX",via LifeworQ,"Full-time, Contractor, and Temp work",False,"Texas, United States",1970-01-01 00:00:00.000000012,True,False,United States,None,NaN,NaN,TWO95 International,['sap'],{'analyst_tools': ['sap']}
237788,Machine Learning Engineer,Machine Learning Engineer,Mexico,via BeBee,Full-time,False,Mexico,1970-01-01 00:00:00.000000012,False,False,Mexico,None,NaN,NaN,International Flavors & Fragrances,"['pytorch', 'tensorflow', 'mxnet']","{'libraries': ['pytorch', 'tensorflow', 'mxnet']}"
731659,Cloud Engineer,Senior Engineers,"Delft, Netherlands",via BeBee,Full-time,False,Netherlands,1970-01-01 00:00:00.000000012,False,False,Netherlands,None,NaN,NaN,Qualinx,"['matlab', 'c++']","{'programming': ['matlab', 'c++']}"
644005,Software Engineer,Graduate Coding Coach,"London, UK",via BeBee,Full-time,False,United Kingdom,1970-01-01 00:00:00.000000012,True,False,United Kingdom,None,NaN,NaN,Harnham,"['snowflake', 'aws', 'azure', 'gcp', 'alteryx']","{'analyst_tools': ['alteryx'], 'cloud': ['snow..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93472,Senior Data Engineer,Senior Data Engineer,"Western Australia, Australia",via Jobrapido.com,Full-time,False,Australia,1970-01-01 00:00:00.000000001,False,False,Australia,None,NaN,NaN,Professional Search Group,"['sql', 't-sql', 'python', 'java', 'r', 'power...","{'analyst_tools': ['ssis', 'excel'], 'cloud': ..."
282667,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,1970-01-01 00:00:00.000000001,False,False,India,None,NaN,NaN,ACI Worldwide,"['sql', 'power bi', 'tableau', 'dax']","{'analyst_tools': ['power bi', 'tableau', 'dax..."
93461,Business Analyst,Business IT Analyst (Part Time / Full Time),Singapore,via Emprego.pt,Full-time,False,Singapore,1970-01-01 00:00:00.000000001,False,False,Singapore,None,NaN,NaN,RESILIENCE COLLECTIVE LTD.,"['c', 'power bi']","{'analyst_tools': ['power bi'], 'programming':..."
524112,Data Scientist,Data Scientist,"Houston, TX",via Trabajo.org,Full-time,False,"Texas, United States",1970-01-01 00:00:00.000000001,False,True,United States,None,NaN,NaN,Channel Factory,"['python', 'r', 'scala', 'sql', 'redshift', 's...","{'cloud': ['redshift'], 'libraries': ['scikit-..."
203943,Data Scientist,Data Scientist,"Denver, CO",via Adzuna,Full-time,False,Sudan,1970-01-01 00:00:00.000000001,False,True,Sudan,None,NaN,NaN,BP,"['python', 'azure', 'aws']","{'cloud': ['azure', 'aws'], 'programming': ['p..."

In [ ]:
df.drop(labels='job_posted_date', axis = 1)  # removes info for column - when given name its column

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
203943,Data Scientist,Data Scientist,"Denver, CO",via Adzuna,Full-time,False,Sudan,False,True,Sudan,None,NaN,NaN,BP,"['python', 'azure', 'aws']","{'cloud': ['azure', 'aws'], 'programming': ['p..."
709496,Data Engineer,Data Engineer,"West Bromwich, UK",via My ArkLaMiss Jobs,Full-time,False,United Kingdom,True,False,United Kingdom,None,NaN,NaN,X4 Group,None,None
709492,Senior Data Scientist,AIML - Senior Data Scientist - Siri and Inform...,"Santa Clara, CA",via Trabajo.org,Full-time,False,"California, United States",False,True,United States,None,NaN,NaN,Apple Inc.,"['python', 'hadoop', 'spark']","{'libraries': ['hadoop', 'spark'], 'programmin..."
709486,Data Engineer,Data Engineer,"McLean, VA",via LinkedIn,Full-time,False,Georgia,False,True,United States,None,NaN,NaN,Piper Companies,"['bash', 'python', 'java', 'scala', 'hadoop', ...","{'libraries': ['hadoop', 'spark', 'kafka'], 'o..."
30379,Senior Data Analyst,General Assurance Data Analytics – Manager,Singapore,via LinkedIn,Full-time,False,Singapore,True,False,Singapore,None,NaN,NaN,PwC Singapore,"['sql', 'vba', 'tableau', 'qlik', 'power bi', ...","{'analyst_tools': ['tableau', 'qlik', 'power b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320501,Software Engineer,Junior Software Engineer,"Toronto, ON, Canada",via SimplyHired,Full-time,False,Canada,False,False,Canada,None,NaN,NaN,San Data System,None,None
765254,Software Engineer,Onsite Network Security Support Engineer,"Nairobi, Kenya",via BeBee Kenya,Full-time,False,Kenya,False,False,Kenya,None,NaN,NaN,NTT Ltd,None,None
439849,Senior Data Engineer,Senior Data Engineer,"Sydney NSW, Australia",via LinkedIn,Full-time,False,Australia,False,False,Australia,None,NaN,NaN,Workforce Australia for Individuals,"['python', 'sql', 'aws', 'spark', 'airflow', '...","{'cloud': ['aws'], 'libraries': ['spark', 'air..."
447335,Data Scientist,Data Science + Python Midior,"Madrid, Spain",via BeBee,Full-time,False,Spain,False,False,Spain,None,NaN,NaN,SG Tech,"['python', 'pandas', 'tensorflow']","{'libraries': ['pandas', 'tensorflow'], 'progr..."
573693,Business Analyst,QA Engineer,"Ramos Mejía, Buenos Aires Province, Argentina",via BeBee,Full-time,False,Argentina,True,False,Argentina,None,NaN,NaN,Veritran,['jira'],{'async': ['jira']}

In [ ]:
df.drop(labels=5, axis=0)  # removes info for row 5 - when given numbers its rows

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
203943,Data Scientist,Data Scientist,"Denver, CO",via Adzuna,Full-time,False,Sudan,1970-01-01 00:00:00.000000001,False,True,Sudan,None,NaN,NaN,BP,"['python', 'azure', 'aws']","{'cloud': ['azure', 'aws'], 'programming': ['p..."
709496,Data Engineer,Data Engineer,"West Bromwich, UK",via My ArkLaMiss Jobs,Full-time,False,United Kingdom,1970-01-01 00:00:00.000000001,True,False,United Kingdom,None,NaN,NaN,X4 Group,None,None
709492,Senior Data Scientist,AIML - Senior Data Scientist - Siri and Inform...,"Santa Clara, CA",via Trabajo.org,Full-time,False,"California, United States",1970-01-01 00:00:00.000000001,False,True,United States,None,NaN,NaN,Apple Inc.,"['python', 'hadoop', 'spark']","{'libraries': ['hadoop', 'spark'], 'programmin..."
709486,Data Engineer,Data Engineer,"McLean, VA",via LinkedIn,Full-time,False,Georgia,1970-01-01 00:00:00.000000001,False,True,United States,None,NaN,NaN,Piper Companies,"['bash', 'python', 'java', 'scala', 'hadoop', ...","{'libraries': ['hadoop', 'spark', 'kafka'], 'o..."
30379,Senior Data Analyst,General Assurance Data Analytics – Manager,Singapore,via LinkedIn,Full-time,False,Singapore,1970-01-01 00:00:00.000000001,True,False,Singapore,None,NaN,NaN,PwC Singapore,"['sql', 'vba', 'tableau', 'qlik', 'power bi', ...","{'analyst_tools': ['tableau', 'qlik', 'power b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320501,Software Engineer,Junior Software Engineer,"Toronto, ON, Canada",via SimplyHired,Full-time,False,Canada,1970-01-01 00:00:00.000000012,False,False,Canada,None,NaN,NaN,San Data System,None,None
765254,Software Engineer,Onsite Network Security Support Engineer,"Nairobi, Kenya",via BeBee Kenya,Full-time,False,Kenya,1970-01-01 00:00:00.000000012,False,False,Kenya,None,NaN,NaN,NTT Ltd,None,None
439849,Senior Data Engineer,Senior Data Engineer,"Sydney NSW, Australia",via LinkedIn,Full-time,False,Australia,1970-01-01 00:00:00.000000012,False,False,Australia,None,NaN,NaN,Workforce Australia for Individuals,"['python', 'sql', 'aws', 'spark', 'airflow', '...","{'cloud': ['aws'], 'libraries': ['spark', 'air..."
447335,Data Scientist,Data Science + Python Midior,"Madrid, Spain",via BeBee,Full-time,False,Spain,1970-01-01 00:00:00.000000012,False,False,Spain,None,NaN,NaN,SG Tech,"['python', 'pandas', 'tensorflow']","{'libraries': ['pandas', 'tensorflow'], 'progr..."
573693,Business Analyst,QA Engineer,"Ramos Mejía, Buenos Aires Province, Argentina",via BeBee,Full-time,False,Argentina,1970-01-01 00:00:00.000000012,True,False,Argentina,None,NaN,NaN,Veritran,['jira'],{'async': ['jira']}

In [ ]:
df.drop(labels=5)   # axis =1 = column ; axis = 0 - row ------- optional

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
203943,Data Scientist,Data Scientist,"Denver, CO",via Adzuna,Full-time,False,Sudan,1970-01-01 00:00:00.000000001,False,True,Sudan,None,NaN,NaN,BP,"['python', 'azure', 'aws']","{'cloud': ['azure', 'aws'], 'programming': ['p..."
709496,Data Engineer,Data Engineer,"West Bromwich, UK",via My ArkLaMiss Jobs,Full-time,False,United Kingdom,1970-01-01 00:00:00.000000001,True,False,United Kingdom,None,NaN,NaN,X4 Group,None,None
709492,Senior Data Scientist,AIML - Senior Data Scientist - Siri and Inform...,"Santa Clara, CA",via Trabajo.org,Full-time,False,"California, United States",1970-01-01 00:00:00.000000001,False,True,United States,None,NaN,NaN,Apple Inc.,"['python', 'hadoop', 'spark']","{'libraries': ['hadoop', 'spark'], 'programmin..."
709486,Data Engineer,Data Engineer,"McLean, VA",via LinkedIn,Full-time,False,Georgia,1970-01-01 00:00:00.000000001,False,True,United States,None,NaN,NaN,Piper Companies,"['bash', 'python', 'java', 'scala', 'hadoop', ...","{'libraries': ['hadoop', 'spark', 'kafka'], 'o..."
30379,Senior Data Analyst,General Assurance Data Analytics – Manager,Singapore,via LinkedIn,Full-time,False,Singapore,1970-01-01 00:00:00.000000001,True,False,Singapore,None,NaN,NaN,PwC Singapore,"['sql', 'vba', 'tableau', 'qlik', 'power bi', ...","{'analyst_tools': ['tableau', 'qlik', 'power b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320501,Software Engineer,Junior Software Engineer,"Toronto, ON, Canada",via SimplyHired,Full-time,False,Canada,1970-01-01 00:00:00.000000012,False,False,Canada,None,NaN,NaN,San Data System,None,None
765254,Software Engineer,Onsite Network Security Support Engineer,"Nairobi, Kenya",via BeBee Kenya,Full-time,False,Kenya,1970-01-01 00:00:00.000000012,False,False,Kenya,None,NaN,NaN,NTT Ltd,None,None
439849,Senior Data Engineer,Senior Data Engineer,"Sydney NSW, Australia",via LinkedIn,Full-time,False,Australia,1970-01-01 00:00:00.000000012,False,False,Australia,None,NaN,NaN,Workforce Australia for Individuals,"['python', 'sql', 'aws', 'spark', 'airflow', '...","{'cloud': ['aws'], 'libraries': ['spark', 'air..."
447335,Data Scientist,Data Science + Python Midior,"Madrid, Spain",via BeBee,Full-time,False,Spain,1970-01-01 00:00:00.000000012,False,False,Spain,None,NaN,NaN,SG Tech,"['python', 'pandas', 'tensorflow']","{'libraries': ['pandas', 'tensorflow'], 'progr..."
573693,Business Analyst,QA Engineer,"Ramos Mejía, Buenos Aires Province, Argentina",via BeBee,Full-time,False,Argentina,1970-01-01 00:00:00.000000012,True,False,Argentina,None,NaN,NaN,Veritran,['jira'],{'async': ['jira']}

In [ ]:
df.dropna(subset = 'salary_year_avg')     # drops na values in given column

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
30380,Data Analyst,SQL DEVELOPER / DATA ANALYST (Insurance indust...,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",1970-01-01 00:00:00.000000001,True,True,United States,year,110000.0,NaN,Robert Half,"['sql', 'ssis']","{'analyst_tools': ['ssis'], 'programming': ['s..."
709819,Data Analyst,Business/Data Analyst Manager- AVP -C12-Hybrid,"New Port Richey, FL",via Big Country Jobs,Full-time,False,"Florida, United States",1970-01-01 00:00:00.000000001,False,False,United States,year,101540.0,NaN,Citi,['sql'],{'programming': ['sql']}
709506,Data Engineer,Principal Big Data Engineer,"Warsaw, Poland",via Ai-Jobs.net,Full-time,False,Poland,1970-01-01 00:00:00.000000001,False,False,Poland,year,45000.0,NaN,Bosch Group,"['python', 'oracle', 'spark', 'hadoop', 'kafka...","{'cloud': ['oracle'], 'libraries': ['spark', '..."
710079,Data Scientist,Data Scientist,"Stafford, VA",via Indeed,Full-time,False,"New York, United States",1970-01-01 00:00:00.000000001,False,True,United States,year,119550.0,NaN,Booz Allen Hamilton,"['r', 'python', 'sql', 'nosql', 'mysql', 'hado...","{'analyst_tools': ['sharepoint'], 'databases':..."
710182,Data Analyst,Junior Data Analyst,"Gland, Switzerland",via Ai-Jobs.net,Full-time,False,Switzerland,1970-01-01 00:00:00.000000001,True,False,Switzerland,year,51000.0,NaN,Swissquote,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165424,Data Engineer,Data Engineer,"Greenwood Village, CO",via Indeed,Full-time,False,"New York, United States",1970-01-01 00:00:00.000000012,False,True,United States,year,125000.0,NaN,FullSpeed Automotive,"['sql', 'python', 'powershell', 'azure', 'data...","{'cloud': ['azure', 'databricks'], 'libraries'..."
82064,Data Engineer,Sr. Data Engineer,Pennsylvania,via Indeed,Full-time,False,Sudan,1970-01-01 00:00:00.000000012,False,False,Sudan,year,108900.0,NaN,Kraft Heinz Company,"['python', 'r', 'sql', 'nosql', 'snowflake', '...","{'analyst_tools': ['tableau', 'alteryx', 'powe..."
320672,Machine Learning Engineer,Machine Learning Engineer,"San Francisco, CA",via LinkedIn,Full-time,False,"California, United States",1970-01-01 00:00:00.000000012,False,False,United States,year,212500.0,NaN,X4 Technology,"['python', 'sql']","{'programming': ['python', 'sql']}"
156517,Data Analyst,Investment Data and Analytics Manager,Anywhere,via Get.It,Full-time,True,"Illinois, United States",1970-01-01 00:00:00.000000012,False,True,United States,year,125000.0,NaN,Get It Recruit - Information Technology,"['vba', 'sql', 'python', 'r', 'excel', 'tablea...","{'analyst_tools': ['excel', 'tableau', 'altery..."
447359,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",1970-01-01 00:00:00.000000012,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."

In [ ]:
df.describe()  # --- #  overal statistical values

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   1970-01-01 00:00:00.000000006    123286.274072        47.016598
min    1970-01-01 00:00:00.000000001     15000.000000         8.000000
25%    1970-01-01 00:00:00.000000003     90000.000000        27.500000
50%    1970-01-01 00:00:00.000000006    115000.000000        45.980000
75%    1970-01-01 00:00:00.000000009    150000.000000        61.159996
max    1970-01-01 00:00:00.000000012    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [ ]:
df.count()  # total values in each column

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

In [ ]:
df['salary_year_avg'].median()

115000.0

In [ ]:
df['salary_year_avg'].min()

15000.0

In [ ]:
min_salary = df['salary_year_avg'].idxmin()

In [ ]:
df.iloc[min_salary]    # shows the calculated min salary in certain value for 1 row with all column names

job_title_short                           Data Analyst
job_title                   Institutional Data Analyst
job_location                            Romeoville, IL
job_via                             via Higher Ed Jobs
job_schedule_type                            Full-time
job_work_from_home                               False
search_location                Illinois, United States
job_posted_date          1970-01-01 00:00:00.000000011
job_no_degree_mention                            False
job_health_insurance                             False
job_country                              United States
salary_rate                                       None
salary_year_avg                                    NaN
salary_hour_avg                                    NaN
company_name                          Lewis University
job_skills                                        None
job_type_skills                                   None
Name: 306649, dtype: object

In [ ]:
df['job_title_short'].value_counts()    # shows number of diff values in column

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [ ]:
df.groupby('job_title_short')['salary_year_avg'].min()    # 1st ([]) value, then [[]] value

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

In [ ]:
df.groupby(['job_title_short', 'job_country'])['salary_year_avg'].min()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      63000.0
                                   ...
Software Engineer  Venezuela          NaN
                   Vietnam        28000.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

In [ ]:
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']].min()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   16500.0           10.835
Cloud Engineer                     42000.0           18.500
Data Analyst                       25000.0            8.000
Data Engineer                      15000.0            8.000
Data Scientist                     27000.0            8.000
Machine Learning Engineer          30000.0           10.000
Senior Data Analyst                30000.0           13.000
Senior Data Engineer               35000.0           12.500
Senior Data Scientist              45000.0           17.500
Software Engineer                  28000.0           11.000

In [ ]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max', 'mean'])

                               min       max           mean
job_title_short
Business Analyst           16500.0  387460.0   91082.612833
Cloud Engineer             42000.0  280000.0  111268.453846
Data Analyst               25000.0  650000.0   93841.907854
Data Engineer              15000.0  525000.0  130125.604250
Data Scientist             27000.0  960000.0  135988.837171
Machine Learning Engineer  30000.0  325000.0  126774.315972
Senior Data Analyst        30000.0  425000.0  113911.363665
Senior Data Engineer       35000.0  425000.0  145840.611624
Senior Data Scientist      45000.0  890000.0  154206.292996
Software Engineer          28000.0  375000.0  113393.760054

In [ ]:
print(df['job_posted_date'].iloc[0])

1970-01-01 00:00:00.000000001